version: "1.0"
environment: development
server:
   name: "fmanager"
   port: ":3000"
   html: "/app/dist/*.html"
   static: "/app/dist/assets"
database:
   dns: "host=localhost user=postgres password=mysecretpassword dbname=auth port=5432 sslmode=disable TimeZone=Asia/Shanghai"