version: '3.4'

services:
  fmanager:
    image: fmanager:1.0
    container_name: fmanager
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: always
    networks:
      - dev
networks:
  dev:
    external: true