
# userinfo
GET https://43.134.115.113:5000/connect/userinfo
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkY5RUYxOUVGRjhCNEJEQjcxQzY0Qzc0NDYxN0RGMjQwIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3MzU4ODA3MzQsImV4cCI6MTczNTg4NDMzNCwiaXNzIjoiaHR0cHM6Ly80My4xMzQuMTE1LjExMzo1MDAwIiwiYXVkIjoiaHR0cHM6Ly80My4xMzQuMTE1LjExMzo1MDAwL3Jlc291cmNlcyIsImNsaWVudF9pZCI6ImludGVyYWN0aXZlIiwic3ViIjoiNjIwOTM3MDktNzFmNS00ZDk5LWI5OTYtZWU2ZDczYzM1NjE5IiwiYXV0aF90aW1lIjoxNzM1ODczMTczLCJpZHAiOiJsb2NhbCIsImp0aSI6IjYwRjlFMTFERkVEQTAyQUIwM0QyRUUxNUQ4RDdDMDhBIiwic2lkIjoiMzI4NjkwNEU5Qjg1Rjk0N0IxQUYxRDM0REQwMUE4RjciLCJpYXQiOjE3MzU4ODA3MzQsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiXSwiYW1yIjpbInB3ZCJdfQ.UJSAYi7lAALCrioHo6B8dFdCdX2mLBt_H-WHU9ysPDXh88HIV68V1H5fBXz43F0R0jTMcQczTSTpSxdj6ySIZN6fFmOzOoj5-43vPfrppLtj-vF7uRTmrEaO64HwMhI9labfvl_c8AnvS3t6MhenvnfObkSFLB7SVinJFDV0vUdD7ItgDq6QJeKbkWBBDYHhjn5U_4Jt710Cz7Hg3SlRt8-1Vq6tTCHc1OWv_ohBqS-k4tBC5bDWGD8LtzN7LWrzivJDi9U2t3N4YPRGyvkm1EqziARxeIpJt4heBK8otxwTO9KpjsyggLxh4Ls3MJV_Pg4yq4oFbnnaBy5bdvb1Sg